apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clixx-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: grafana.deji-stack.com
      http:
        paths:
          - path: /clixx(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: clixx-service
                port:
                  number: 80

